name: my_project
version: 1.0.0
config-version: 2
profile: my_project

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target"]

models:
  my_project:
    +materialized: view